name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:

  test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: prepare
      run: |
        rustup component add clippy
        sudo apt-get install tcl8.6 tclx
    - name: Fmt
      run: make fmt
    - name: Clippy
      run: make clippy
    - name: Unit test
      run: make unit-test
    - name: Test
      run: make test

